// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjputtmpcmiunaqbbebe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcHV0dG1wY21pdW5hcWJiZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjcwNTAsImV4cCI6MjA1Nzg0MzA1MH0.eu-vK2i1XWMWBUhBNFAxb5N_7Jfcps19-njgZarQZYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);